### PR TITLE
Fix tile boundary rendering issue

### LINKED ISSUE #114: Tile Placement Bug
There has been a bug with placing tiles correctly on the screen, leading to there being an empty line where there shouldn't be, both in the horizontal and vertical directions. The vertical lines have been removed, but horizontal lines sometimes appear as well.

### PR DESCRIPTION
**Pull request by Didgy74**
Resolves #114

### CODE REVIEW

**Comment by cecilianor** [comment]
I'm working on reviewing this PR right now. I may update some of the documentation before approving the merge, let's see how this goes.

File: lib/Rendering.cpp [hunk 1]
```diff
@@ -7,6 +7,121 @@
...
+    double pixelWidth;
+};
+
+/*!
+ * \internal
+ *
+ * \brief The TilePosCalculator class
+ * is a helper class for positioning tiles within the viewport.
+ */
+struct TilePosCalculator {
```
Comment (cecilianor) [inline lib/Rendering.cpp:28]: Do we change TilePosCalculator to a `class`  instead of a `struct`? The documentation states it's a class, and since it has private fields, I think it's better to make it a class instead of a struct. I can sort this out, just let me know. @Didgy74
